### ISSUE TITLE
Editing + deleting a list item

### ISSUE THREAD

**Issue by Watson-B** [ezl/todo#12]
@yassinya As discussed in Slack, when a user clicks on a list item, we want it to convert to an input field, so that it can be edited freely.
![input-edit-clicked](https://user-images.githubusercontent.com/65913664/155013049-32ecd2d1-4e5e-4d26-88e6-3e05246dc83a.png)
In the instance a user highlights a list item and hits delete on their keyboard, the list item should be removed upon clicking out of the input field, so that there are no residual empty list items.
![input-edit-highlight](https://user-images.githubusercontent.com/65913664/155013200-520bcd75-975e-4fb6-8401-538643c3cc18.png)
![input-edit-deleted](https://user-images.githubusercontent.com/65913664/155013205-b9c41bb1-6764-4cca-868e-4619e15a4f9b.png)

**Comment by ezl** [comment]
I tested this and it doesn't work quite as expected. Currently, the behavior I see is:

1. create an item (works as expected)
2. edit that item (click it, turns into an input -- as expected)
3. delete all the content in that item - does NOT do as expected -- shows placeholder text for new item CREATION. I think it should show nothing)
4. save with no content - does NOT do as expected. I expected the item to disappear from the board. Instead, an EMPTY item with checkbox and no content stays in the list.

I described the intended actions for step 3 and 4 above -- please lmk if you have any questions @yassinya

**Comment by ezl** [comment]
confirmed. looks great.
