### ISSUE TITLE
Tag Menu

### ISSUE THREAD

**Issue by Watson-B** [ezl/todo#13]
This is a future issue for sometime down the road, adding it here to document it. Eventually @ezl would like to move to tag customization similar to notion. 
![image](https://user-images.githubusercontent.com/65913664/155009194-449cd551-db59-4559-b5bf-7071595799d8.png)
Clicking the tag menu, will open a menu asking the user how they would like to sort tags (most used, alphabetical, recency), the toggle to show completed tags, and then each tag listed out with the option to color code it, delete it, or reorder it.

**Comment by ezl** [comment]
closing. created more detailed tickets for this.
