### ISSUE TITLE
add user / persistence stuff for syncing between devices

### ISSUE THREAD

**Issue by ezl** [ezl/todo#23]
so users can sync their to do lists between devices

v1 of allowing users to authenticate:
https://www.figma.com/file/MHW4pKE13g4L46Tvq7i8TQ/Bad-To-Do?node-id=1001%3A7

there are a lot of important questions in this. how will we persist this? where? (obviously need an external data store for this)

how will we handle conflicts? for example, what if i create an item on my laptop and another item on my phone at the same time?

how will we handle syncing? is this realtime? on refresh?

**Comment by ezl** [comment]
Some other items I noticed while testing syncing:

[] in the DOM notification to check your inbox, there is a space in the word "the" -- "please click t he verification..."
[] make the DOM notification a little bit longer -- maybe 5 seconds?
[] when typing email address, allow "enter" to submit this (currently need to click the disk icon)
[] use badtodo.com domain for email address from confirmation email (flowstify) + confirmation page (dilaaal)
[] question: what's the backoff/retry interval on the pending invitation in the browser?
[] mobile experience for entering email isn't ideal - when I click on the input to enter my email address on my phone, it zooms in to the input field - this hides the "save" icon
[] mobile input field for entering email doesn't span the full width -- on desktop, it spans the full width of the settings section, then on valid email address, it animates showing the save icon. on mobile, there's just whitespace to the right of the icon.

**Comment by yassinya** [comment]
@ezl  It currently checks status of the verification every 5 seconds (starts as soon as the email is successfully sent), then stops after 5 minutes. This restarts again when the page gains focus again.

I’m aware of the issues on small screens, I’m currently working on it
