### ISSUE TITLE
import / export -- add ability for users to import/export their lists

### ISSUE THREAD

**Issue by ezl** [ezl/todo#3]
(A) it makes it so if they want to move their data somewhere else, they can
(B) it makes it so that if they delete the extension and reinstall, it will work
(C) in the future, it'll make it possible for us to sync lists between multiple devices

**Comment by ezl** [comment]
just make this an option in the settings cog

**Comment by Watson-B** [comment]
@yassinya I talked with @ezl about the import / export ability for users, and we'd like these options to live in the settings menu. The design for the updated settings menu with these options can [be found in Figma here](https://www.figma.com/file/MHW4pKE13g4L46Tvq7i8TQ/To-Do-(working)?node-id=836%3A256)
![updated-settings](https://user-images.githubusercontent.com/65913664/155621462-e2232201-3b77-4383-9fbf-ddcc558ac4f3.png)
