### ISSUE TITLE
deselect all on multiselect

### ISSUE THREAD

**Issue by ezl** [ezl/todo#33]
UI for this

**Comment by Watson-B** [comment]
![image](https://user-images.githubusercontent.com/65913664/156819466-b2f7a552-c5a0-4c99-a878-59337a758054.png)
Discussed this with @ezl , he'd like to change the select action text to an interactive deselect 'x' once items have been selected. Design can be found [here in Figma](https://www.figma.com/file/MHW4pKE13g4L46Tvq7i8TQ/To-Do-(working)?node-id=761%3A2)

**Comment by ezl** [comment]
@yassinya I reviewed this. I see that in your implementation, it is a little bit lighter (opacity maybe?) and has squared corners.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/157627/163692883-9cd20217-4ff5-4003-969a-80837af793ad.png">

In the actual figma file, the orange is solid (same color, no opacity):

<img width="860" alt="image" src="https://user-images.githubusercontent.com/157627/163692865-a7fb43b1-0667-4851-b2f4-dc754db54794.png">

I'd like to keep the interaction color usage always the same whenever possible

**Comment by yassinya** [comment]
@ezl  It's the same color but looks like one of its parent has a low opacity, I’ll take care of that!
