### ISSUE TITLE
improve mobile/responsive experience

### ISSUE THREAD

**Issue by ezl** [ezl/todo#39]
- increase padding around the "new task" input field so it doesn't go all the way to the edge on narrow viewports
- on multi-select on touch devices, slide ALL to do items off canvas so we can do multiselect (currently only one sliding off, so a second item can't be selected via multiselect). I would recommend doing this so it looks like it's an "off canvas" section that slides over. (if this isn't clear, lmk, and I'll try to explain better)

Question:
- on narrow viewports, how do NON-touch devices get to multi-select? Currently, it shrinks down to look like mobile, but it doesn't seem like there's a way to expose the select circles.

**Comment by yassinya** [comment]
@ezl Regarding small viewports without touch functionality, what if we add support for long-press (with mouse)?

**Comment by ezl** [comment]
@yassinya I was thinking about this. I decided that for now, we just won't support anything on narrow viewports without touch functionality.

Basically, if a user has a desktop and they choose to keep the narrow view, then they just don't have access to the multiselect functionality. They can just widen their viewport if they need to do those things.

**Comment by ezl** [comment]
looks good!

A few comments / questions:

1. on long press on my phone, i find that it ALSOO triggers the native OS behavior to select the text of the to do list item. this is confusing because it FIRST triggers the text selection, then AFTER that, the slide occurs.

(A) is it possible to restrict the native device behavior?
(B) alternatively, what if we make the off screen slide behavior trigger *sooner* so that it doesn't happen AFTER thae native device highlight behavior

On this item -- please just let me know what you think / if there are other options that you recommend.

2. the "slide to reveal select buttons" behavior is really good. however, on pressing "cancel", there is no animation. Can you animate this sliding back at the same speed as the slide to reveal please?

**Comment by yassinya** [comment]
@ezl 
1. Yes, we can temporarily prevent native text selection while sliding. I’ll look into this and take care of it as soon as possible
2. That is definitely possible, I’ll add another animation for sliding back
3. Roger that!

**Comment by ezl** [comment]
perfect. let's do that then.

1. just prevent the native text selection while sliding.
2. animate sliding back
3. autoselect the longpressed item.

:)
