### ISSUE TITLE
Implement some sort of notification system

### ISSUE THREAD

**Issue by ezl** [ezl/todo#53]
For example, when we want to give user feedback on things like:

"you've connected to the server!"
"your data has been imported from your file"

are there any existing notification libraries you recommend, @yassinya 

Not married to this style, but was thinking something like this:
Placement - https://www.figma.com/file/MHW4pKE13g4L46Tvq7i8TQ/Bad-To-Do?node-id=1079%3A853
Styles - https://www.figma.com/file/MHW4pKE13g4L46Tvq7i8TQ/Bad-To-Do?node-id=1079%3A799

**Comment by yassinya** [comment]
Sorry @ezl , I somehow missed that you tagged me here.

We could use the same library we are currently using, it’s highly customizable so we should be able to style it however we need!

**Comment by ezl** [comment]
no problem @yassinya :)

Try to implement using the styles above then please! :)

**Comment by yassinya** [comment]
@ezl I will!

**Comment by yassinya** [comment]
I added two types of notifications:
1. One which has buttons, won’t disappear until the user clicks on one of them
2. Another that does not require any action from the user and disappears after few second

To see them in action, delete a tag or an item

Looking forward to your thoughts @ezl : )

**Comment by ezl** [comment]
@yassinya awesome - how do I trigger the 2 different styles so I can see it in action?

**Comment by yassinya** [comment]
@ezl Delete any item and tag to see them in action

**Comment by ezl** [comment]
@yassinya looks good - when I delete a tag though, when I click the confirm button, the notification does not disappear.

https://www.loom.com/share/f907c9c0d3094a3b92a55f9cb16194de

**Comment by yassinya** [comment]
I made a quick fix, should be good now @ezl !
