### ISSUE TITLE
hide (or blur) UX elements when not in use

### ISSUE THREAD

**Issue by ezl** [ezl/todo#63]
1. for example, on long press on mobile, the task multiselect radio buttons are displayed.

now at this stage, search and "create an item" should not be usable. so blur these from view.

2. when settings is selected, blur all task content, for example: https://monosnap.com/file/a7NTuHw1bf5wAH1KhX92N7ejqZD6Bx (not pixelated, but a nice smooth css blur)

3. when search bar is active, hide task creation input area - can't remove from DOM or do display:none, because we don't want the tasks to all slide UP -- we want it to just fade out and be invisible, but still take up the same vertical height so that the tasks themselves don't move up

**Comment by ezl** [comment]
@yassinya did this change somehow get reverted? As I was trying other tests on the site just now, the blur doesn't seem to be occurring anymore.

**Comment by yassinya** [comment]
I just noticed that, I’m looking into it now @ezl

**Comment by yassinya** [comment]
Should be good now! @ezl
