### ISSUE TITLE
On small screens, add a FAB to create new items

### ISSUE THREAD

**Issue by yassinya** [ezl/todo#68]
1. Hide current item creation input on mobile 
2. Add a FAB (Floating Action Button), and show an input to add a new item when its clicked
3. The new input (when displayed) should take the full width/height of the screen, and have a button to dismiss it

**Comment by ezl** [comment]
@yassinya to be clear, i think this should only be on mobile TOUCH devices. So for example, on desktop devices with narrow viewports, just keep the existing narrow entry field at the top.

other than that, i love the idea, and think it makes total sense for mobile -- your 1/2/3 is already perfect.
