### ISSUE TITLE
bug: grouping when re-ordering by drag doesn't work as expected

### ISSUE THREAD

**Issue by ezl** [ezl/todo#75]
https://www.loom.com/share/40d0d603af5941a99a8feef5737ad489?from_recorder=1&focus_title=1

**Comment by yassinya** [comment]
@ezl  I just tested an old version and it is working as expected, so I must have broken something in the latest update.
I’ll look into this and resolve it!

**Comment by ezl** [comment]
@yassinya great thank you :)
