### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Watson-B** [ezl/todo#8]

**Comment by Watson-B** [comment]
@yassinya @ezl wants to go ahead and add a simple search to inbox and tasks. The designs can be found in [Figma here](https://www.figma.com/file/MHW4pKE13g4L46Tvq7i8TQ/To-Do-(working)?node-id=761%3A2699). In the default state, we will just indicate that search is possible with the magnifying glass icon.
![dark-scheme](https://user-images.githubusercontent.com/65913664/155007463-3f755bae-b05e-4a95-8368-b100429a78a0.png)
![light-scheme](https://user-images.githubusercontent.com/65913664/155007465-bbd20678-a9ca-4708-9f9b-6adc5b1f6728.png)

When a user has clicked the search icon, the input will fade in and expand as the tags fade out. Clicking cancel reverses the transition of the search input, and returns the screen to the default state.
![search-focused-dark](https://user-images.githubusercontent.com/65913664/155007522-62c12c9a-cc45-41fd-8b70-012ea32bf097.png)
![search-focused-light](https://user-images.githubusercontent.com/65913664/155007529-4ad769a2-6bdf-4613-bc88-6c596ce3d25e.png)

After the user has started typing, the 'x' will fade in. Clicking it will clear the current string entered into the search field. 

![search-string-light](https://user-images.githubusercontent.com/65913664/155007599-399414bc-60a7-456e-8c87-00dc065ffbe0.png)
![search-string-dark](https://user-images.githubusercontent.com/65913664/155007600-a8ab6631-0a14-49df-9699-2461fbbdc815.png)

**Comment by ezl** [comment]
this is perfect. thanks @Watson-B
