### ISSUE TITLE
there's some sort of bug with tag creation - i think it may be related to the preceding string/text somehow, or somehow the position counter is inaccurate due to the URL in the task text?

### ISSUE THREAD

**Issue by ezl** [ezl/todo#91]
https://www.loom.com/share/7bf59127915049afac8e48d1c8c188fe

**Comment by ezl** [comment]
@yassinya i see this is marked as ready for review -- out of curiosity, what was the problem and how did you fix it?

**Comment by yassinya** [comment]
@ezl It turns out the problem was that the “&” character was being converted to `&amp;` when setting the value of the contenteditable input using `innerHTML`. 
I had to switch over to using `textContent` in order to solve it

**Comment by ezl** [comment]
Got it! Thanks for explaining!
