### ISSUE TITLE
what happens if i delete a tag that is in existing items?

### ISSUE THREAD

**Issue by ezl** [ezl/todo#93]
This is a bit of a question, just so I can understand the behavior.

For example, let's say there are 3 active tasks with the tag "#eric".

Then I go to the tag settings and DELETE the tag "#eric".

What will happen? Will the tasks still be there? Will they be displayed with the text #eric, but it won't be recognized as a tag? What happens in this case?

**Comment by yassinya** [comment]
@ezl When a tag is deleted, its tasks are not deleted.
We just detach them from the tag after deleting it.

They won’t be highlighted anymore, and they will appear as plain/normal text

**Comment by ezl** [comment]
sounds good 👍
